// Auto-generated from BIM - Digital Twin 2025.xlsx
// Generated on: 2026-01-03T01:38:01.028Z

export const PROJECTS_FROM_EXCEL = [
  {
    "id": "K8CT1",
    "code": "25001",
    "name": "Tây Hồ Tây Lô K8CT1",
    "client": "CÔNG TY TNHH DAEWOO ENGINEERING & CONSTRUCTION VIỆT NAM",
    "location": "Hồ Chí Minh",
    "manager": "NV006",
    "projectGroup": "BIM",
    "constructionType": "Dân dụng",
    "constructionLevel": "I",
    "scale": "156.368 m²",
    "capitalSource": "NonStateBudget",
    "status": "InProgress",
    "progress": 35,
    "budget": 4730000000,
    "spent": 3440000000,
    "deadline": "2023-01-31",
    "members": [],
    "description": "1/ Mô hình BIM giai đoạn TKCS (Nộp hồ sơ BIM thẩm định)\n2/ Video diễn họa\n3/ Báo cáo va chạm và các vấn đề trong giai đoạn TKCS\n4/ Khối lượng trích xuất từ mô hình\n5/ Mô hình BIM giai đoạn TKKT\n6/ Video diễn họa TKKT\n7/ Báo cáo va chạm và các vấn đề trong giai đoạn TKKT\n8/ Khối lượng trích xuất từ mô hình TKKT\n9/ Mô hình BIM giai đoạn TKTC\n10/ Báo cáo va chạm và các vấn đề trong giai đoạn TKTC\n11/ Khối lượng trích xuất từ mô hình TKTC\""
  },
  {
    "id": "K8HH1",
    "code": "25002",
    "name": "Tây Hồ Tây Lô K8HH1",
    "client": "CÔNG TY TNHH DAEWOO ENGINEERING & CONSTRUCTION VIỆT NAM",
    "location": "Hồ Chí Minh",
    "manager": "NV006",
    "projectGroup": "BIM",
    "constructionType": "Dân dụng",
    "constructionLevel": "I",
    "scale": "N/A",
    "capitalSource": "NonStateBudget",
    "status": "InProgress",
    "progress": 40,
    "budget": 4180000000,
    "spent": 4119200000,
    "deadline": "2023-01-31",
    "members": [],
    "description": ""
  },
  {
    "id": "K2CT1",
    "code": "25003",
    "name": "Tây Hồ Tây Lô K2CT1",
    "client": "CÔNG TY TNHH DAEWOO ENGINEERING & CONSTRUCTION VIỆT NAM",
    "location": "Hồ Chí Minh",
    "manager": "NV006",
    "projectGroup": "BIM",
    "constructionType": "Dân dụng",
    "constructionLevel": "I",
    "scale": "194.206,01 m²",
    "capitalSource": "NonStateBudget",
    "status": "InProgress",
    "progress": 65,
    "budget": 4860000000,
    "spent": 2430000000,
    "deadline": "2023-08-15",
    "members": [],
    "description": "1/ Mô hình BIM giai đoạn NCKT (Mô hình, Khối lượng, bản vẽ) 09/04/2025\n2/ Báo cáo va chạm và các vấn đề trong giai đoạn NCKT\n3/ Video diễn họa \n4/ Trích xuất Khối lượng chính\n5/ Mô hình BIM giai đoạn TKTC\n6/ Báo cáo va chạm và các vấn đề trong giai đoạn TKTC\n7/ Trích xuất khối lượng chính\""
  },
  {
    "id": "H1HH1",
    "code": "25004",
    "name": "Tây Hồ Tây Lô H1HH1",
    "client": "CÔNG TY TNHH DAEWOO ENGINEERING & CONSTRUCTION VIỆT NAM",
    "location": "Hồ Chí Minh",
    "manager": "NV006",
    "projectGroup": "BIM",
    "constructionType": "Dân dụng",
    "constructionLevel": "I",
    "scale": "108.117 m²",
    "capitalSource": "NonStateBudget",
    "status": "InProgress",
    "progress": 39,
    "budget": 4266000000,
    "spent": 2559600000,
    "deadline": "2024-09-11",
    "members": [],
    "description": "1/ Mô hình BIM giai đoạn TKKT\n2/ Báo cáo va chạm và các vấn đề trong giai đoạn TKKT\n3/ Video diễn họa \n4/ Trích xuất Khối lượng chính\n5/ Mô hình BIM giai đoạn TKTC\n6/ Báo cáo va chạm và các vấn đề trong giai đoạn TKTC\n7/ Video diễn họa \n8/ Trích xuất Khối lượng chính\""
  },
  {
    "id": "B1CC4",
    "code": "25005",
    "name": "Tây Hồ Tây Lô B1CC4",
    "client": "CÔNG TY TNHH DAEWOO ENGINEERING & CONSTRUCTION VIỆT NAM",
    "location": "Hồ Chí Minh",
    "manager": "NV006",
    "projectGroup": "BIM",
    "constructionType": "Dân dụng",
    "constructionLevel": "I",
    "scale": "N/A",
    "capitalSource": "NonStateBudget",
    "status": "InProgress",
    "progress": 58,
    "budget": 3132000000,
    "spent": 626400000,
    "deadline": "2024-09-11",
    "members": [],
    "description": "1/ Mô hình BIM giai đoạn TKKT\n2/ Báo cáo va chạm và các vấn đề trong giai đoạn TKKT\n3/ Video diễn họa \n4/ Trích xuất Khối lượng chính\n5/ Mô hình BIM giai đoạn TKTC\n6/ Báo cáo va chạm và các vấn đề trong giai đoạn TKTC\n7/ Video diễn họa \n8/ Trích xuất Khối lượng chính\"\"\""
  },
  {
    "id": "LOTT-PL26",
    "code": "25006",
    "name": "Eco Smart City Plot 2-6",
    "client": "CÔNG TY TNHH LOTTE PROPERTIES HCMC",
    "location": "Hồ Chí Minh",
    "manager": "NV006",
    "projectGroup": "BIM",
    "constructionType": "Dân dụng",
    "constructionLevel": "I",
    "scale": "N/A",
    "capitalSource": "NonStateBudget",
    "status": "InProgress",
    "progress": 31,
    "budget": 5095744000,
    "spent": 2091293347,
    "deadline": "2024-02-19",
    "members": [],
    "description": ""
  },
  {
    "id": "LOTT-PL24",
    "code": "25007",
    "name": "Eco Smart City Plot 2-4",
    "client": "CÔNG TY TNHH LOTTE PROPERTIES HCMC",
    "location": "Hồ Chí Minh",
    "manager": "NV006",
    "projectGroup": "BIM",
    "constructionType": "Dân dụng",
    "constructionLevel": "I",
    "scale": "N/A",
    "capitalSource": "NonStateBudget",
    "status": "InProgress",
    "progress": 34,
    "budget": 1759027200,
    "spent": 176405299,
    "deadline": "2024-02-19",
    "members": [],
    "description": ""
  },
  {
    "id": "LOTT-PL22",
    "code": "25008",
    "name": "Eco Smart City Plot 2-2",
    "client": "CÔNG TY TNHH LOTTE PROPERTIES HCMC",
    "location": "Hồ Chí Minh",
    "manager": "NV006",
    "projectGroup": "BIM",
    "constructionType": "Dân dụng",
    "constructionLevel": "I",
    "scale": "N/A",
    "capitalSource": "NonStateBudget",
    "status": "InProgress",
    "progress": 66,
    "budget": 2035168000,
    "spent": 104404118,
    "deadline": "2025-01-01",
    "members": [],
    "description": ""
  },
  {
    "id": "LOTT-PL21",
    "code": "25009",
    "name": "Eco Smart City Plot 2-1",
    "client": "CÔNG TY TNHH JUNGLIM ARCHITECTURE VIETNAM",
    "location": "Hồ Chí Minh",
    "manager": "NV006",
    "projectGroup": "BIM",
    "constructionType": "Dân dụng",
    "constructionLevel": "I",
    "scale": "N/A",
    "capitalSource": "NonStateBudget",
    "status": "InProgress",
    "progress": 72,
    "budget": 661000000,
    "spent": 213664000,
    "deadline": "2025-08-31",
    "members": [],
    "description": ""
  },
  {
    "id": "LOTT-PL23",
    "code": "25010",
    "name": "Eco Smart City Plot 2-3",
    "client": "CÔNG TY TNHH JUNGLIM ARCHITECTURE VIETNAM",
    "location": "Hồ Chí Minh",
    "manager": "NV006",
    "projectGroup": "BIM",
    "constructionType": "Dân dụng",
    "constructionLevel": "I",
    "scale": "N/A",
    "capitalSource": "NonStateBudget",
    "status": "InProgress",
    "progress": 65,
    "budget": 1440000000,
    "spent": 0,
    "deadline": "2025-09-30",
    "members": [],
    "description": ""
  }
];

export const CONTRACTS_FROM_EXCEL = [
  {
    "id": "C001",
    "contractNumber": "01/PPXD-CICHĐ2023",
    "projectId": "K8CT1",
    "type": "Tư vấn BIM",
    "partyA": "CÔNG TY TNHH DAEWOO ENGINEERING & CONSTRUCTION VIỆT NAM",
    "partyARepresentative": "Kwon Soon Jae ",
    "partyB": "Công ty CP Công nghệ và Tư vấn CIC",
    "partyBRepresentative": "Nguyễn Hoàng Hà ",
    "signedDate": "2023-01-31",
    "effectiveDate": "2023-01-31",
    "expiryDate": "2023-01-31",
    "totalValue": 4730000000,
    "paidValue": 3440000000,
    "status": "Active",
    "description": "1/ Mô hình BIM giai đoạn TKCS (Nộp hồ sơ BIM thẩm định)\n2/ Video diễn họa\n3/ Báo cáo va chạm và các vấn đề trong giai đoạn TKCS\n4/ Khối lượng trích xuất từ mô hình\n5/ Mô hình BIM giai đoạn TKKT\n6/ Video diễn họa TKKT\n7/ Báo cáo va chạm và các vấn đề trong giai đoạn TKKT\n8/ Khối lượng trích xuất từ mô hình TKKT\n9/ Mô hình BIM giai đoạn TKTC\n10/ Báo cáo va chạm và các vấn đề trong giai đoạn TKTC\n11/ Khối lượng trích xuất từ mô hình TKTC\"",
    "constructionType": "Dân dụng ",
    "constructionLevel": "I",
    "capitalSource": "Vốn khác"
  },
  {
    "id": "C002",
    "contractNumber": "02/PPXD-CICHĐ2023",
    "projectId": "K8HH1",
    "type": "Tư vấn BIM",
    "partyA": "CÔNG TY TNHH DAEWOO ENGINEERING & CONSTRUCTION VIỆT NAM",
    "partyARepresentative": "Kwon Soon Jae ",
    "partyB": "Công ty CP Công nghệ và Tư vấn CIC",
    "partyBRepresentative": "Nguyễn Hoàng Hà ",
    "signedDate": "2023-01-31",
    "effectiveDate": "2023-01-31",
    "expiryDate": "2023-01-31",
    "totalValue": 4180000000,
    "paidValue": 4119200000,
    "status": "Active",
    "description": "",
    "constructionType": "Dân dụng ",
    "constructionLevel": "I",
    "capitalSource": "Vốn khác"
  },
  {
    "id": "C003",
    "contractNumber": "44/PPXD-CICHĐ2023",
    "projectId": "cc7595fe",
    "type": "Tư vấn BIM",
    "partyA": "CÔNG TY TNHH PHÁT TRIỂN STS VIỆT NAM",
    "partyARepresentative": "Lee Chul Sung",
    "partyB": "Công ty CP Công nghệ và Tư vấn CIC",
    "partyBRepresentative": "Nguyễn Hoàng Hà ",
    "signedDate": "2023-06-13",
    "effectiveDate": "2023-06-13",
    "expiryDate": "2023-06-13",
    "totalValue": 6264000000,
    "paidValue": 1879200000,
    "status": "Active",
    "description": "",
    "constructionType": "Dân dụng ",
    "constructionLevel": "I",
    "capitalSource": "Vốn khác"
  },
  {
    "id": "C004",
    "contractNumber": "48/PPXD-CICHĐ2023",
    "projectId": "Dự án BVI",
    "type": "Tư vấn BIM",
    "partyA": "CÔNG TY TNHH INROS LACKNER VIỆT NAM",
    "partyARepresentative": "N/A",
    "partyB": "Công ty CP Công nghệ và Tư vấn CIC",
    "partyBRepresentative": "Nguyễn Hoàng Hà",
    "signedDate": "2023-06-12",
    "effectiveDate": "2023-06-12",
    "expiryDate": "2025-01-01",
    "totalValue": 153576000,
    "paidValue": 76788000,
    "status": "Active",
    "description": "",
    "constructionType": "Dân dụng ",
    "constructionLevel": "I",
    "capitalSource": "Vốn khác"
  },
  {
    "id": "C005",
    "contractNumber": "73/PPXD-CICHĐ2023",
    "projectId": "c2536118",
    "type": "Tư vấn BIM",
    "partyA": "BAN QUẢN LÝ DỰ ÁN ĐẦU TƯ XÂY DỰNG CÔNG TRÌNH DÂN DỤNG VÀ CÔNG NGHIỆP TỈNH SƠN LA",
    "partyARepresentative": "Nguyễn Văn Thể ",
    "partyB": "Công ty CP Công nghệ và Tư vấn CIC",
    "partyBRepresentative": "Nguyễn Hoàng Hà ",
    "signedDate": "2023-08-08",
    "effectiveDate": "2023-08-08",
    "expiryDate": "2023-08-08",
    "totalValue": 972981000,
    "paidValue": 972981000,
    "status": "Draft",
    "description": "",
    "constructionType": "Hạ tầng kỹ thuật",
    "constructionLevel": "III",
    "capitalSource": "Vốn đầu tư công"
  },
  {
    "id": "C006",
    "contractNumber": "74/PPXD-CICHĐ2023",
    "projectId": "K2CT1",
    "type": "Tư vấn BIM",
    "partyA": "CÔNG TY TNHH DAEWOO ENGINEERING & CONSTRUCTION VIỆT NAM",
    "partyARepresentative": "Kwon Soon Jae ",
    "partyB": "Công ty CP Công nghệ và Tư vấn CIC",
    "partyBRepresentative": "Nguyễn Hoàng Hà ",
    "signedDate": "2023-08-15",
    "effectiveDate": "2023-08-15",
    "expiryDate": "2023-08-15",
    "totalValue": 4860000000,
    "paidValue": 2430000000,
    "status": "Active",
    "description": "1/ Mô hình BIM giai đoạn NCKT (Mô hình, Khối lượng, bản vẽ) 09/04/2025\n2/ Báo cáo va chạm và các vấn đề trong giai đoạn NCKT\n3/ Video diễn họa \n4/ Trích xuất Khối lượng chính\n5/ Mô hình BIM giai đoạn TKTC\n6/ Báo cáo va chạm và các vấn đề trong giai đoạn TKTC\n7/ Trích xuất khối lượng chính\"",
    "constructionType": "Dân dụng ",
    "constructionLevel": "I",
    "capitalSource": "Vốn khác"
  },
  {
    "id": "C007",
    "contractNumber": "01/BIM-CICHĐ2024 LÔ 2.2",
    "projectId": "LOTT-PL22",
    "type": "Tư vấn BIM",
    "partyA": "CÔNG TY TNHH LOTTE PROPERTIES HCMC",
    "partyARepresentative": "Jun Sung Ho",
    "partyB": "Công ty CP Công nghệ và Tư vấn CIC",
    "partyBRepresentative": "Nguyễn Hoàng Hà ",
    "signedDate": "2024-02-19",
    "effectiveDate": "2024-02-19",
    "expiryDate": "2025-01-01",
    "totalValue": 2035168000,
    "paidValue": 104404118,
    "status": "Active",
    "description": "Tư vấn BIM cho dự án theo các giai đoạn: Thiết kế cơ sở, Hồ sơ thiết kế bản vẽ thi công, Giai đoạn xây dựng (dịch vụ tùy chọn) và Giai đoạn hoàn thành dự án.",
    "constructionType": "Dân dụng ",
    "constructionLevel": "I",
    "capitalSource": "Vốn khác"
  },
  {
    "id": "C008",
    "contractNumber": "01/BIM-CICHĐ2024 LÔ 2.4",
    "projectId": "LOTT-PL24",
    "type": "Tư vấn BIM",
    "partyA": "CÔNG TY TNHH LOTTE PROPERTIES HCMC",
    "partyARepresentative": "Jun Sung Ho",
    "partyB": "Công ty CP Công nghệ và Tư vấn CIC",
    "partyBRepresentative": "Nguyễn Hoàng Hà ",
    "signedDate": "2024-02-19",
    "effectiveDate": "2024-02-19",
    "expiryDate": "2024-02-19",
    "totalValue": 1759027200,
    "paidValue": 176405299,
    "status": "Active",
    "description": "Tư vấn BIM cho dự án theo các giai đoạn: Thiết kế cơ sở, Hồ sơ thiết kế bản vẽ thi công, Giai đoạn xây dựng (dịch vụ tùy chọn) và Giai đoạn hoàn thành dự án.",
    "constructionType": "Dân dụng ",
    "constructionLevel": "I",
    "capitalSource": "Vốn khác"
  },
  {
    "id": "C009",
    "contractNumber": "01/BIM-CICHĐ2024 LÔ 2.6",
    "projectId": "LOTT-PL26",
    "type": "Tư vấn BIM",
    "partyA": "CÔNG TY TNHH LOTTE PROPERTIES HCMC",
    "partyARepresentative": "Jun Sung Ho",
    "partyB": "Công ty CP Công nghệ và Tư vấn CIC",
    "partyBRepresentative": "Nguyễn Hoàng Hà ",
    "signedDate": "2024-02-19",
    "effectiveDate": "2024-02-19",
    "expiryDate": "2024-02-19",
    "totalValue": 5095744000,
    "paidValue": 2091293347,
    "status": "Active",
    "description": "Tư vấn BIM cho dự án theo các giai đoạn: Thiết kế cơ sở, Hồ sơ thiết kế bản vẽ thi công, Giai đoạn xây dựng (dịch vụ tùy chọn) và Giai đoạn hoàn thành dự án.",
    "constructionType": "Dân dụng ",
    "constructionLevel": "I",
    "capitalSource": "Vốn khác"
  },
  {
    "id": "C010",
    "contractNumber": "02/BIM-CICHĐ2024",
    "projectId": "55b1301c",
    "type": "Tư vấn đào tạo BIM",
    "partyA": "HASEKO CORPORATION",
    "partyARepresentative": "Takashi Tsuruta",
    "partyB": "Công ty CP Công nghệ và Tư vấn CIC",
    "partyBRepresentative": "Lương Thành Hưng ",
    "signedDate": "2024-03-12",
    "effectiveDate": "2024-03-12",
    "expiryDate": "2024-03-12",
    "totalValue": 270000000,
    "paidValue": 270000000,
    "status": "Active",
    "description": "Bên B có trách nhiệm cập nhật mô hình BIM (gồm mô hình bê tông và cốt thép) , trích xuất khối lượng từ mô hình BIM , tạo danh sách va chạm (Clash Report) , và xuất khối lượng kết cấu theo mẫu BOQ của Bên A",
    "constructionType": "Dân dụng ",
    "constructionLevel": "II",
    "capitalSource": "Vốn khác"
  }
];

export const CUSTOMERS_FROM_EXCEL = [
  {
    "id": "CÔNG TY TNHH DAEWOO ENGINEERING & CONSTRUCTION VIỆT NAM",
    "name": "CÔNG TY TNHH DAEWOO ENGINEERING & CONSTRUCTION VIỆT NAM",
    "representative": "Kwon Soon Jae ",
    "type": "Doanh nghiệp"
  },
  {
    "id": "CÔNG TY TNHH PHÁT TRIỂN STS VIỆT NAM",
    "name": "CÔNG TY TNHH PHÁT TRIỂN STS VIỆT NAM",
    "representative": "Lee Chul Sung",
    "type": "Doanh nghiệp"
  },
  {
    "id": "CÔNG TY TNHH INROS LACKNER VIỆT NAM",
    "name": "CÔNG TY TNHH INROS LACKNER VIỆT NAM",
    "representative": "N/A",
    "type": "Doanh nghiệp"
  },
  {
    "id": "BAN QUẢN LÝ DỰ ÁN ĐẦU TƯ XÂY DỰNG CÔNG TRÌNH DÂN DỤNG VÀ CÔNG NGHIỆP TỈNH SƠN LA",
    "name": "BAN QUẢN LÝ DỰ ÁN ĐẦU TƯ XÂY DỰNG CÔNG TRÌNH DÂN DỤNG VÀ CÔNG NGHIỆP TỈNH SƠN LA",
    "representative": "Nguyễn Văn Thể ",
    "type": "Doanh nghiệp"
  },
  {
    "id": "CÔNG TY TNHH LOTTE PROPERTIES HCMC",
    "name": "CÔNG TY TNHH LOTTE PROPERTIES HCMC",
    "representative": "Jun Sung Ho",
    "type": "Doanh nghiệp"
  },
  {
    "id": "HASEKO CORPORATION",
    "name": "HASEKO CORPORATION",
    "representative": "Takashi Tsuruta",
    "type": "Doanh nghiệp"
  },
  {
    "id": "TỔNG CÔNG TY ĐẦU TƯ PHÁT TRIỂN NHÀ Ở VÀ ĐÔ THỊ - CÔNG TY TNHH",
    "name": "TỔNG CÔNG TY ĐẦU TƯ PHÁT TRIỂN NHÀ Ở VÀ ĐÔ THỊ - CÔNG TY TNHH",
    "representative": "Nguyễn Tuấn Anh ",
    "type": "Doanh nghiệp"
  },
  {
    "id": "CÔNG TY CỔ PHẦN 319.5",
    "name": "CÔNG TY CỔ PHẦN 319.5",
    "representative": "Đỗ Văn Chính ",
    "type": "Doanh nghiệp"
  },
  {
    "id": "BAN QUẢN LÝ DỰ ÁN ĐẦU TƯ XÂY DỰNG CÔNG TRÌNH DÂN DỤNG VÀ HẠ TẦNG KHU VỰC TỈNH HÀ TĨNH",
    "name": "BAN QUẢN LÝ DỰ ÁN ĐẦU TƯ XÂY DỰNG CÔNG TRÌNH DÂN DỤNG VÀ HẠ TẦNG KHU VỰC TỈNH HÀ TĨNH",
    "representative": "N/A",
    "type": "Doanh nghiệp"
  },
  {
    "id": "SỞ XÂY DỰNG TỈNH VĨNH PHÚC",
    "name": "SỞ XÂY DỰNG TỈNH VĨNH PHÚC",
    "representative": "N/A",
    "type": "Doanh nghiệp"
  }
];
