import { Contract, ContractStatus } from '../types';

// Default values for contracts
const defaultContractFields: Partial<Contract> = {
  sideAPosition: '',
  sideAMst: '',
  sideAStaff: '',
  sideBPosition: '',
  sideBMst: '',
  sideBBank: '',
  wipValue: 0,
  lawApplied: 'Luật Xây dựng 2014',
  deliveryMethod: 'Trọn gói',
  warrantyPeriod: '12 tháng',
  mainTasks: ['Tư vấn BIM', 'Thiết kế mô hình'],
  fileFormats: 'RVT, IFC, PDF',
  acceptanceStandard: 'ISO 19650',
  penaltyRate: '0.05%',
  maxPenalty: '8%',
  disputeResolution: 'Trọng tài',
  transactions: []
};

// Raw contract data - will be merged with defaults
const RAW_CONTRACTS: Partial<Contract>[] = [
  // HĐ 02/BIM-CICHD2025 - Cơ sở nghiên cứu các viện nghiên cứu xã hội
  {
    id: "02/BIM-CICHD2025",
    code: "02/BIM-CICHD2025",
    projectName: "Cơ sở nghiên cứu các viện nghiên cứu xã hội",
    projectId: "P-001",
    sideAName: "BAN QUẢN LÝ DỰ ÁN ĐẦU TƯ XÂY DỰNG CHUYÊN NGÀNH",
    sideARep: "Nguyễn In",
    sideAPosition: "",
    sideAMst: "",
    sideAStaff: "",
    sideBName: "CÔNG TY CP CÔNG NGHỆ VÀ TƯ VẤN CIC",
    sideBRep: "Nguyễn Hoàng Hà",
    sideBPosition: "Tổng Giám đốc",
    sideBMst: "",
    sideBBank: "",
    packageName: "Tư vấn BIM",
    signedDate: "2025-03-11",
    startDate: "2025-03-11",
    endDate: "2025-11-03",
    duration: "12 tháng",
    totalValue: 381800000,
    paidValue: 114540000,
    remainingValue: 267260000,
    wipValue: 0,
    vatIncluded: true,
    advancePayment: 30,
    status: ContractStatus.ACTIVE,
    contractType: "Output",
    capitalSource: "StateBudget",
    constructionType: "Dân dụng",
    deliveryMethod: "Trọn gói",
    penaltyRate: "0.05%",
    maxPenalty: "8%",
    disputeResolution: "Trọng tài",
    warrantyPeriod: "12 tháng",
    mainTasks: ["Thiết kế bản vẽ thi công"],
    fileFormats: "RVT, IFC, PDF",
    acceptanceStandard: "ISO 19650",
    lawApplied: "Luật Xây dựng 2014",
    location: "Hà Nội",
    personnel: [{ role: "BIM Manager", name: "Nguyễn Hoàng Hà" }],
    paymentMilestones: [],
    transactions: []
  },
  // HĐ 02.2025/KCNTRAN-YEN - Khu Công nghiệp Trấn Yên
  {
    id: "02.2025/KCNTRAN-YEN",
    code: "02.2025/KCNTRAN-YEN/VIG.CIC",
    projectName: "Khu Công nghiệp Trấn Yên",
    projectId: "P-002",
    sideAName: "BQL DA ĐT XD - CHI NHÁNH TỔNG CÔNG TY VIGLACERA - CTCP",
    sideARep: "Trần Anh Tuấn",
    sideAPosition: "",
    sideBName: "CÔNG TY CP CÔNG NGHỆ VÀ TƯ VẤN CIC",
    sideBRep: "Nguyễn Hoàng Hà",
    sideBPosition: "Tổng Giám đốc",
    packageName: "Tư vấn BIM",
    signedDate: "2025-07-14",
    startDate: "2025-07-14",
    endDate: "2026-03-14",
    duration: "8 tháng",
    totalValue: 259200000,
    paidValue: 77760000,
    remainingValue: 181440000,
    wipValue: 0,
    vatIncluded: true,
    advancePayment: 30,
    status: ContractStatus.ACTIVE,
    contractType: "Output",
    capitalSource: "StateBudget",
    constructionType: "Hạ tầng kỹ thuật",
    deliveryMethod: "Trọn gói",
    location: "Yên Bái",
    personnel: [],
    paymentMilestones: [],
    transactions: []
  },
  // HĐ 04/BIM-CICHD2025 - BV Nhi đồng 1
  {
    id: "04/BIM-CICHD2025",
    code: "04/BIM-CICHD2025",
    projectName: "Xây dựng mới TT chuyên sâu BV Nhi đồng 1",
    projectId: "P-003",
    sideAName: "BQL DA ĐT XD CT DD & CN TP.HCM",
    sideARep: "Huỳnh Thanh Hải",
    sideBName: "CÔNG TY CP CÔNG NGHỆ VÀ TƯ VẤN CIC",
    sideBRep: "Nguyễn Hoàng Hà",
    packageName: "Tư vấn BIM",
    signedDate: "2025-03-20",
    startDate: "2025-03-20",
    endDate: "2026-06-20",
    duration: "15 tháng",
    totalValue: 155000000,
    paidValue: 46500000,
    remainingValue: 108500000,
    vatIncluded: true,
    advancePayment: 30,
    status: ContractStatus.ACTIVE,
    contractType: "Output",
    capitalSource: "StateBudget",
    constructionType: "Dân dụng",
    location: "TP. Hồ Chí Minh",
    personnel: [],
    paymentMilestones: [],
    transactions: []
  },
  // HĐ 07/BIM-CICHD2025 - BV Cà Mau GĐ Thiết kế
  {
    id: "07/BIM-CICHD2025",
    code: "07/BIM-CICHD2025",
    projectName: "Bệnh viện Đa khoa Cà Mau",
    projectId: "P-004",
    sideAName: "CÔNG TY CỔ PHẦN 319.5",
    sideARep: "Nguyễn Ngọc Niệm",
    sideBName: "CÔNG TY CP CÔNG NGHỆ VÀ TƯ VẤN CIC",
    sideBRep: "Lương Thanh Hưng",
    sideBPosition: "Phó TGĐ",
    packageName: "Tư vấn BIM",
    signedDate: "2025-04-18",
    startDate: "2025-04-18",
    endDate: "2025-06-17",
    duration: "12 tháng",
    totalValue: 891000000,
    paidValue: 267300000,
    remainingValue: 623700000,
    vatIncluded: true,
    advancePayment: 30,
    status: ContractStatus.ACTIVE,
    contractType: "Output",
    capitalSource: "StateBudget",
    constructionType: "Dân dụng",
    location: "Cà Mau",
    personnel: [{ role: "BIM Manager", name: "Lương Thanh Hưng" }],
    paymentMilestones: [],
    transactions: []
  },
  // HĐ 08/BIM-CICHD2025 - BV Đa khoa Thái Bình
  {
    id: "08/BIM-CICHD2025",
    code: "08/BIM-CICHD2025",
    projectName: "Đầu tư XD BV Đa khoa tỉnh Thái Bình",
    projectId: "P-005",
    sideAName: "VIỆN KIẾN TRÚC QUỐC GIA",
    sideARep: "Nhật",
    sideBName: "CÔNG TY CP CÔNG NGHỆ VÀ TƯ VẤN CIC",
    sideBRep: "",
    packageName: "Tư vấn BIM",
    signedDate: "2025-04-09",
    startDate: "2025-04-09",
    endDate: "2025-06-23",
    duration: "10 tháng",
    totalValue: 495811000,
    paidValue: 148593300,
    remainingValue: 346717700,
    vatIncluded: true,
    advancePayment: 30,
    status: ContractStatus.ACTIVE,
    contractType: "Output",
    capitalSource: "StateBudget",
    constructionType: "Dân dụng",
    location: "Thái Bình",
    personnel: [],
    paymentMilestones: [],
    transactions: []
  },
  // HĐ 14/BIM-CICHD2025 - Nhà máy gạch Granite
  {
    id: "14/BIM-CICHD2025",
    code: "14/BIM-CICHD2025",
    projectName: "Nhà máy sản xuất gạch Granite Porcelain Premier",
    projectId: "P-006",
    sideAName: "CÔNG TY TNHH XÂY DỰNG VIỆT PANEL",
    sideARep: "Lưu Bình Cii",
    sideBName: "CÔNG TY CP CÔNG NGHỆ VÀ TƯ VẤN CIC",
    sideBRep: "Lương Thành Hưng",
    packageName: "Tư vấn BIM",
    signedDate: "2025-05-08",
    startDate: "2025-05-08",
    endDate: "2025-05-25",
    duration: "6 tháng",
    totalValue: 122000000,
    paidValue: 36600000,
    remainingValue: 85400000,
    vatIncluded: true,
    advancePayment: 30,
    status: ContractStatus.ACTIVE,
    contractType: "Output",
    capitalSource: "NonStateBudget",
    constructionType: "Công nghiệp",
    location: "Vĩnh Phúc",
    personnel: [],
    paymentMilestones: [],
    transactions: []
  },
  // HĐ 09/BIM-CICHD2025 - Suất ăn tàu bay
  {
    id: "09/BIM-CICHD2025",
    code: "09/BIM-CICHD2025",
    projectName: "Suất ăn tàu bay (CKS)",
    projectId: "P-007",
    sideAName: "CÔNG TY CP TV XD CN & ĐT VIỆT NAM (VCC)",
    sideARep: "Ngọc Loan",
    sideBName: "CÔNG TY CP CÔNG NGHỆ VÀ TƯ VẤN CIC",
    sideBRep: "Lương Thành Hưng",
    packageName: "Tư vấn BIM",
    signedDate: "2025-05-02",
    startDate: "2025-05-02",
    endDate: "2025-07-01",
    duration: "8 tháng",
    totalValue: 152545844,
    paidValue: 45763744,
    remainingValue: 106782100,
    vatIncluded: true,
    advancePayment: 30,
    status: ContractStatus.ACTIVE,
    contractType: "Output",
    capitalSource: "NonStateBudget",
    constructionType: "Dân dụng",
    location: "TP. Hồ Chí Minh",
    personnel: [],
    paymentMilestones: [],
    transactions: []
  },
  // HĐ 01/BIM-CICHD2025 - BV Cà Mau GĐ Thi công
  {
    id: "01/BIM-CICHD2025",
    code: "01/BIM-CICHD2025",
    projectName: "Bệnh viện Cà Mau - GĐ Thi công",
    projectId: "P-008",
    sideAName: "CÔNG TY CP SẢN XUẤT CÔNG NGHIỆP XÂY LẮP 3",
    sideARep: "Lã Tiến Lực",
    sideBName: "CÔNG TY CP CÔNG NGHỆ VÀ TƯ VẤN CIC",
    sideBRep: "Lương Hoàng Hà",
    packageName: "Tư vấn BIM",
    signedDate: "2025-06-17",
    startDate: "2025-06-17",
    endDate: "2025-08-31",
    duration: "18 tháng",
    totalValue: 891000000,
    paidValue: 267300000,
    remainingValue: 623700000,
    vatIncluded: true,
    advancePayment: 30,
    status: ContractStatus.ACTIVE,
    contractType: "Output",
    capitalSource: "StateBudget",
    constructionType: "Dân dụng",
    location: "Cà Mau",
    personnel: [],
    paymentMilestones: [],
    transactions: []
  },
  // HĐ 12/BIM-CICHD2025 - BV Bãi Cháy
  {
    id: "12/BIM-CICHD2025",
    code: "12/BIM-CICHD2025",
    projectName: "Bệnh viện Bãi Cháy - TKBVTC",
    projectId: "P-009",
    sideAName: "CÔNG TY CP TƯ VẤN VÀ THIẾT KẾ XD VN (CDC)",
    sideARep: "Trần Tuấn Anh",
    sideBName: "CÔNG TY CP CÔNG NGHỆ VÀ TƯ VẤN CIC",
    sideBRep: "",
    packageName: "Tư vấn BIM",
    signedDate: "2025-04-29",
    startDate: "2025-04-29",
    endDate: "2025-04-25",
    duration: "10 tháng",
    totalValue: 363960000,
    paidValue: 109188000,
    remainingValue: 254772000,
    vatIncluded: true,
    advancePayment: 30,
    status: ContractStatus.ACTIVE,
    contractType: "Output",
    capitalSource: "StateBudget",
    constructionType: "Dân dụng",
    location: "Quảng Ninh",
    personnel: [],
    paymentMilestones: [],
    transactions: []
  },
  // HĐ 25/BIM-CICHD2025 - Cung thiếu nhi TP
  {
    id: "25/BIM-CICHD2025",
    code: "25/BIM-CICHD2025",
    projectName: "Xây dựng Cung thiếu nhi thành phố",
    projectId: "P-010",
    sideAName: "BQL DA ĐT XD CT DD & CN TP.HCM",
    sideARep: "Dương Minh Thủy",
    sideBName: "CÔNG TY CP CÔNG NGHỆ VÀ TƯ VẤN CIC",
    sideBRep: "",
    packageName: "Tư vấn BIM",
    signedDate: "2025-07-17",
    startDate: "2025-07-17",
    endDate: "2025-08-19",
    duration: "18 tháng",
    totalValue: 1999686000,
    paidValue: 599905800,
    remainingValue: 1399780200,
    vatIncluded: true,
    advancePayment: 30,
    status: ContractStatus.ACTIVE,
    contractType: "Output",
    capitalSource: "StateBudget",
    constructionType: "Dân dụng",
    location: "TP. Hồ Chí Minh",
    personnel: [],
    paymentMilestones: [],
    transactions: []
  },
  // HĐ 22/BIM-CICHD2025 - Trường THPT Bãi Cháy
  {
    id: "22/BIM-CICHD2025",
    code: "22/BIM-CICHD2025",
    projectName: "Xây mới Trường THPT Bãi Cháy",
    projectId: "P-011",
    sideAName: "BQL DA ĐT XD CT DD & CN QUẢNG NINH",
    sideARep: "Nguyễn Văn Chí",
    sideBName: "CÔNG TY CP CÔNG NGHỆ VÀ TƯ VẤN CIC",
    sideBRep: "",
    packageName: "Tư vấn BIM",
    signedDate: "2025-06-26",
    startDate: "2025-06-26",
    endDate: "2025-07-25",
    duration: "6 tháng",
    totalValue: 46000000,
    paidValue: 13800000,
    remainingValue: 32200000,
    vatIncluded: true,
    advancePayment: 30,
    status: ContractStatus.ACTIVE,
    contractType: "Output",
    capitalSource: "StateBudget",
    constructionType: "Dân dụng",
    location: "Quảng Ninh",
    personnel: [],
    paymentMilestones: [],
    transactions: []
  },
  // HĐ 17/BIM-CICHD2025 - Trường CĐ nghề TP.HCM
  {
    id: "17/BIM-CICHD2025",
    code: "17/BIM-CICHD2025",
    projectName: "Trường Cao đẳng nghề TP.HCM - CS 2 - GĐ 2",
    projectId: "P-012",
    sideAName: "BQL DA ĐT XD CT DD & CN TP.HCM",
    sideARep: "Dương Minh Thủy",
    sideBName: "CÔNG TY CP CÔNG NGHỆ VÀ TƯ VẤN CIC",
    sideBRep: "Nguyễn Hoàng Hà",
    packageName: "Tư vấn BIM",
    signedDate: "2025-05-19",
    startDate: "2025-05-19",
    endDate: "2025-06-18",
    duration: "10 tháng",
    totalValue: 169500000,
    paidValue: 50850000,
    remainingValue: 118650000,
    vatIncluded: true,
    advancePayment: 30,
    status: ContractStatus.ACTIVE,
    contractType: "Output",
    capitalSource: "StateBudget",
    constructionType: "Dân dụng",
    location: "TP. Hồ Chí Minh",
    personnel: [],
    paymentMilestones: [],
    transactions: []
  },
  // HĐ 24/BIM-CICHD2025 - Suất ăn hàng không Long Thành
  {
    id: "24/BIM-CICHD2025",
    code: "24/BIM-CICHD2025",
    projectName: "Suất ăn hàng không Quốc tế Long Thành",
    projectId: "P-013",
    sideAName: "CÔNG TY CP TV XD CN & ĐT VIỆT NAM",
    sideARep: "Hoàng Thị Ngọc Loan",
    sideBName: "CÔNG TY CP CÔNG NGHỆ VÀ TƯ VẤN CIC",
    sideBRep: "Lương Thành Hưng",
    packageName: "Tư vấn BIM",
    signedDate: "2025-01-31",
    startDate: "2025-01-31",
    endDate: "2026-01-31",
    duration: "24 tháng",
    totalValue: 798560426,
    paidValue: 239448143,
    remainingValue: 559112283,
    vatIncluded: true,
    advancePayment: 30,
    status: ContractStatus.ACTIVE,
    contractType: "Output",
    capitalSource: "NonStateBudget",
    constructionType: "Dân dụng",
    location: "Đồng Nai",
    personnel: [],
    paymentMilestones: [],
    transactions: []
  },
  // HĐ 27/BIM-CICHD2025 - SVĐ Thống Nhất
  {
    id: "27/BIM-CICHD2025",
    code: "27/BIM-CICHD2025",
    projectName: "Cải tạo Sân vận động Thống Nhất",
    projectId: "P-014",
    sideAName: "BQL DA ĐT XD CT DD & CN TP.HCM",
    sideARep: "",
    sideBName: "CÔNG TY CP CÔNG NGHỆ VÀ TƯ VẤN CIC",
    sideBRep: "",
    packageName: "Tư vấn BIM",
    signedDate: "2025-05-15",
    startDate: "2025-05-15",
    endDate: "2025-12-31",
    duration: "8 tháng",
    totalValue: 134615000,
    paidValue: 26923000,
    remainingValue: 107692000,
    vatIncluded: true,
    advancePayment: 20,
    status: ContractStatus.ACTIVE,
    contractType: "Output",
    capitalSource: "StateBudget",
    constructionType: "Dân dụng",
    location: "TP. Hồ Chí Minh",
    personnel: [],
    paymentMilestones: [],
    transactions: []
  },
  // HĐ 29/BIM-CICHD2025 - KCN Tam Anh - An Hòa
  {
    id: "29/BIM-CICHD2025",
    code: "29/BIM-CICHD2025",
    projectName: "Khu Công nghiệp Tam Anh - An Hòa",
    projectId: "P-015",
    sideAName: "CÔNG TY CP KHU CÔNG NGHIỆP VÀ ĐÔ THỊ AN HÒA",
    sideARep: "",
    sideBName: "CÔNG TY CP CÔNG NGHỆ VÀ TƯ VẤN CIC",
    sideBRep: "",
    packageName: "Tư vấn BIM",
    signedDate: "2025-06-01",
    startDate: "2025-06-01",
    endDate: "2026-03-31",
    duration: "10 tháng",
    totalValue: 388800000,
    paidValue: 97200000,
    remainingValue: 291600000,
    vatIncluded: true,
    advancePayment: 25,
    status: ContractStatus.ACTIVE,
    contractType: "Output",
    capitalSource: "NonStateBudget",
    constructionType: "Công nghiệp",
    location: "Quảng Nam",
    personnel: [],
    paymentMilestones: [],
    transactions: []
  },
  // HĐ 28/BIM-CICHD2025 - Dự án TC03
  {
    id: "28/BIM-CICHD2025",
    code: "28/BIM-CICHD2025",
    projectName: "Tòa nhà TC03",
    projectId: "P-016",
    sideAName: "TỔNG CÔNG TY ĐẦU TƯ PHÁT TRIỂN NHÀ VÀ ĐÔ THỊ",
    sideARep: "",
    sideBName: "CÔNG TY CP CÔNG NGHỆ VÀ TƯ VẤN CIC",
    sideBRep: "",
    packageName: "Tư vấn BIM",
    signedDate: "2025-04-20",
    startDate: "2025-04-20",
    endDate: "2025-09-30",
    duration: "6 tháng",
    totalValue: 180000000,
    paidValue: 81000000,
    remainingValue: 99000000,
    vatIncluded: true,
    advancePayment: 45,
    status: ContractStatus.ACTIVE,
    contractType: "Output",
    capitalSource: "NonStateBudget",
    constructionType: "Dân dụng",
    location: "Hà Nội",
    personnel: [],
    paymentMilestones: [],
    transactions: []
  },
  // HĐ 33/BIM-CICHD2025 - Trường CĐ Y tế Bạch Mai TKCS
  {
    id: "33/BIM-CICHD2025",
    code: "33/BIM-CICHD2025",
    projectName: "Trường Cao đẳng Y tế Bạch Mai - TKCS",
    projectId: "P-017",
    sideAName: "VĂN PHÒNG TƯ VẤN & CHUYỂN GIAO CÔNG NGHỆ XÂY DỰNG",
    sideARep: "",
    sideBName: "CÔNG TY CP CÔNG NGHỆ VÀ TƯ VẤN CIC",
    sideBRep: "",
    packageName: "Tư vấn BIM",
    signedDate: "2025-02-15",
    startDate: "2025-02-15",
    endDate: "2025-04-30",
    duration: "3 tháng",
    totalValue: 126584000,
    paidValue: 126584000,
    remainingValue: 0,
    vatIncluded: true,
    advancePayment: 30,
    status: ContractStatus.COMPLETED,
    contractType: "Output",
    capitalSource: "StateBudget",
    constructionType: "Dân dụng",
    location: "Hà Nội",
    personnel: [],
    paymentMilestones: [],
    transactions: []
  },
  // HĐ 34/BIM-CICHD2025 - Trường CĐ Y tế Bạch Mai TKBVTC
  {
    id: "34/BIM-CICHD2025",
    code: "34/BIM-CICHD2025",
    projectName: "Trường Cao đẳng Y tế Bạch Mai - TKBVTC",
    projectId: "P-018",
    sideAName: "VĂN PHÒNG TƯ VẤN & CHUYỂN GIAO CÔNG NGHỆ XÂY DỰNG",
    sideARep: "",
    sideBName: "CÔNG TY CP CÔNG NGHỆ VÀ TƯ VẤN CIC",
    sideBRep: "",
    packageName: "Tư vấn BIM",
    signedDate: "2025-05-01",
    startDate: "2025-05-01",
    endDate: "2025-08-31",
    duration: "6 tháng",
    totalValue: 816644000,
    paidValue: 244993200,
    remainingValue: 571650800,
    vatIncluded: true,
    advancePayment: 30,
    status: ContractStatus.ACTIVE,
    contractType: "Output",
    capitalSource: "StateBudget",
    constructionType: "Dân dụng",
    location: "Hà Nội",
    personnel: [],
    paymentMilestones: [],
    transactions: []
  },
  // HĐ 05/BIM-CICHD2025 - Eco Smart City Lô 2-1
  {
    id: "05/BIM-CICHD2025-PL21",
    code: "05/BIM-CICHD2025",
    projectName: "Eco Smart City Plot 2-1",
    projectId: "P-019",
    sideAName: "CÔNG TY TNHH JUNGLIM ARCHITECTURE VIETNAM",
    sideARep: "",
    sideBName: "CÔNG TY CP CÔNG NGHỆ VÀ TƯ VẤN CIC",
    sideBRep: "",
    packageName: "Tư vấn BIM",
    signedDate: "2025-03-01",
    startDate: "2025-03-01",
    endDate: "2026-06-30",
    duration: "16 tháng",
    totalValue: 661000000,
    paidValue: 264400000,
    remainingValue: 396600000,
    vatIncluded: true,
    advancePayment: 40,
    status: ContractStatus.ACTIVE,
    contractType: "Output",
    capitalSource: "NonStateBudget",
    constructionType: "Dân dụng",
    location: "TP. Hồ Chí Minh",
    personnel: [],
    paymentMilestones: [],
    transactions: []
  },
  // HĐ Eco Smart City Lô 2-2
  {
    id: "05/BIM-CICHD2025-PL22",
    code: "05.2/BIM-CICHD2025",
    projectName: "Eco Smart City Plot 2-2",
    projectId: "P-020",
    sideAName: "CÔNG TY TNHH JUNGLIM ARCHITECTURE VIETNAM",
    sideARep: "",
    sideBName: "CÔNG TY CP CÔNG NGHỆ VÀ TƯ VẤN CIC",
    sideBRep: "",
    packageName: "Tư vấn BIM",
    signedDate: "2025-03-15",
    startDate: "2025-03-15",
    endDate: "2026-09-30",
    duration: "18 tháng",
    totalValue: 1440000000,
    paidValue: 504000000,
    remainingValue: 936000000,
    vatIncluded: true,
    advancePayment: 35,
    status: ContractStatus.ACTIVE,
    contractType: "Output",
    capitalSource: "NonStateBudget",
    constructionType: "Dân dụng",
    location: "TP. Hồ Chí Minh",
    personnel: [],
    paymentMilestones: [],
    transactions: []
  },
  // HĐ Eco Smart City Lô 2-5
  {
    id: "05/BIM-CICHD2025-PL25",
    code: "05.5/BIM-CICHD2025",
    projectName: "Eco Smart City Plot 2-5",
    projectId: "P-021",
    sideAName: "CÔNG TY TNHH JUNGLIM ARCHITECTURE VIETNAM",
    sideARep: "",
    sideBName: "CÔNG TY CP CÔNG NGHỆ VÀ TƯ VẤN CIC",
    sideBRep: "",
    packageName: "Tư vấn BIM",
    signedDate: "2025-04-01",
    startDate: "2025-04-01",
    endDate: "2026-12-31",
    duration: "21 tháng",
    totalValue: 1482000000,
    paidValue: 444600000,
    remainingValue: 1037400000,
    vatIncluded: true,
    advancePayment: 30,
    status: ContractStatus.ACTIVE,
    contractType: "Output",
    capitalSource: "NonStateBudget",
    constructionType: "Dân dụng",
    location: "TP. Hồ Chí Minh",
    personnel: [],
    paymentMilestones: [],
    transactions: []
  },
  // HĐ 21/BIM-CICHD2025 - Bảo tàng Hà Tĩnh
  {
    id: "21/BIM-CICHD2025",
    code: "21/BIM-CICHD2025",
    projectName: "Bảo tàng Hà Tĩnh",
    projectId: "P-022",
    sideAName: "BQL DA ĐT XD CT DD & HT HÀ TĨNH",
    sideARep: "",
    sideBName: "CÔNG TY CP CÔNG NGHỆ VÀ TƯ VẤN CIC",
    sideBRep: "",
    packageName: "Tư vấn BIM",
    signedDate: "2025-03-01",
    startDate: "2025-03-01",
    endDate: "2025-10-31",
    duration: "8 tháng",
    totalValue: 456169000,
    paidValue: 273701400,
    remainingValue: 182467600,
    vatIncluded: true,
    advancePayment: 60,
    status: ContractStatus.ACTIVE,
    contractType: "Output",
    capitalSource: "StateBudget",
    constructionType: "Dân dụng",
    location: "Hà Tĩnh",
    personnel: [],
    paymentMilestones: [],
    transactions: []
  },
  // HĐ 35/BIM-CICHD2025 - Học viện Ngân hàng TKCS
  {
    id: "35/BIM-CICHD2025",
    code: "35/BIM-CICHD2025",
    projectName: "Học viện Ngân hàng - TKCS",
    projectId: "P-023",
    sideAName: "VĂN PHÒNG TƯ VẤN & CHUYỂN GIAO CÔNG NGHỆ XÂY DỰNG",
    sideARep: "",
    sideBName: "CÔNG TY CP CÔNG NGHỆ VÀ TƯ VẤN CIC",
    sideBRep: "",
    packageName: "Tư vấn BIM",
    signedDate: "2025-02-01",
    startDate: "2025-02-01",
    endDate: "2025-05-15",
    duration: "4 tháng",
    totalValue: 138738000,
    paidValue: 138738000,
    remainingValue: 0,
    vatIncluded: true,
    advancePayment: 30,
    status: ContractStatus.COMPLETED,
    contractType: "Output",
    capitalSource: "StateBudget",
    constructionType: "Dân dụng",
    location: "Hà Nội",
    personnel: [],
    paymentMilestones: [],
    transactions: []
  },
  // HĐ 36/BIM-CICHD2025 - Học viện Ngân hàng TKBVTC
  {
    id: "36/BIM-CICHD2025",
    code: "36/BIM-CICHD2025",
    projectName: "Học viện Ngân hàng - TKBVTC",
    projectId: "P-024",
    sideAName: "VĂN PHÒNG TƯ VẤN & CHUYỂN GIAO CÔNG NGHỆ XÂY DỰNG",
    sideARep: "",
    sideBName: "CÔNG TY CP CÔNG NGHỆ VÀ TƯ VẤN CIC",
    sideBRep: "",
    packageName: "Tư vấn BIM",
    signedDate: "2025-05-20",
    startDate: "2025-05-20",
    endDate: "2025-11-30",
    duration: "7 tháng",
    totalValue: 864536000,
    paidValue: 259360800,
    remainingValue: 605175200,
    vatIncluded: true,
    advancePayment: 30,
    status: ContractStatus.ACTIVE,
    contractType: "Output",
    capitalSource: "StateBudget",
    constructionType: "Dân dụng",
    location: "Hà Nội",
    personnel: [],
    paymentMilestones: [],
    transactions: []
  },
  // HĐ 37/BIM-CICHD2025 - KCN Minh Châu
  {
    id: "37/BIM-CICHD2025",
    code: "37/BIM-CICHD2025",
    projectName: "Khu Công nghiệp Minh Châu",
    projectId: "P-025",
    sideAName: "CÔNG TY CP THỊNH VƯỢNG MINH CHÂU",
    sideARep: "",
    sideBName: "CÔNG TY CP CÔNG NGHỆ VÀ TƯ VẤN CIC",
    sideBRep: "",
    packageName: "Tư vấn BIM",
    signedDate: "2025-06-01",
    startDate: "2025-06-01",
    endDate: "2026-06-30",
    duration: "12 tháng",
    totalValue: 100000000,
    paidValue: 30000000,
    remainingValue: 70000000,
    vatIncluded: true,
    advancePayment: 30,
    status: ContractStatus.ACTIVE,
    contractType: "Output",
    capitalSource: "NonStateBudget",
    constructionType: "Công nghiệp",
    location: "Hưng Yên",
    personnel: [],
    paymentMilestones: [],
    transactions: []
  },
  // HĐ 38/BIM-CICHD2025 - Khu nhà ở 486 Ngọc Hồi
  {
    id: "38/BIM-CICHD2025",
    code: "38/BIM-CICHD2025",
    projectName: "Khu nhà ở tại số 486 Ngọc Hồi",
    projectId: "P-026",
    sideAName: "CÔNG TY CỔ PHẦN THIẾT KẾ XÂY DỰNG STELLAR",
    sideARep: "",
    sideBName: "CÔNG TY CP CÔNG NGHỆ VÀ TƯ VẤN CIC",
    sideBRep: "",
    packageName: "Tư vấn BIM",
    signedDate: "2025-04-01",
    startDate: "2025-04-01",
    endDate: "2027-03-31",
    duration: "24 tháng",
    totalValue: 3448000000,
    paidValue: 1034400000,
    remainingValue: 2413600000,
    vatIncluded: true,
    advancePayment: 30,
    status: ContractStatus.ACTIVE,
    contractType: "Output",
    capitalSource: "NonStateBudget",
    constructionType: "Dân dụng",
    location: "Hà Nội",
    personnel: [],
    paymentMilestones: [],
    transactions: []
  },
  // HĐ 39/BIM-CICHD2025 - Nhà văn hóa thanh niên
  {
    id: "39/BIM-CICHD2025",
    code: "39/BIM-CICHD2025",
    projectName: "Nhà văn hóa thanh niên",
    projectId: "P-027",
    sideAName: "BQL DA ĐT XD CT DD & CN TP.HCM",
    sideARep: "",
    sideBName: "CÔNG TY CP CÔNG NGHỆ VÀ TƯ VẤN CIC",
    sideBRep: "",
    packageName: "Tư vấn BIM",
    signedDate: "2025-06-01",
    startDate: "2025-06-01",
    endDate: "2026-03-31",
    duration: "10 tháng",
    totalValue: 2069600000,
    paidValue: 517400000,
    remainingValue: 1552200000,
    vatIncluded: true,
    advancePayment: 25,
    status: ContractStatus.ACTIVE,
    contractType: "Output",
    capitalSource: "StateBudget",
    constructionType: "Dân dụng",
    location: "TP. Hồ Chí Minh",
    personnel: [],
    paymentMilestones: [],
    transactions: []
  },
  // HĐ 43/BIM-CICHD2025 - Trung tâm cấp cứu 115
  {
    id: "43/BIM-CICHD2025",
    code: "43/BIM-CICHD2025",
    projectName: "Trung tâm cấp cứu 115 Cơ sở 2",
    projectId: "P-028",
    sideAName: "BQL DA ĐT XD CT DD & CN TP.HCM",
    sideARep: "",
    sideBName: "CÔNG TY CP CÔNG NGHỆ VÀ TƯ VẤN CIC",
    sideBRep: "",
    packageName: "Tư vấn BIM",
    signedDate: "2025-04-15",
    startDate: "2025-04-15",
    endDate: "2025-09-30",
    duration: "6 tháng",
    totalValue: 678025710,
    paidValue: 203407713,
    remainingValue: 474617997,
    vatIncluded: true,
    advancePayment: 30,
    status: ContractStatus.ACTIVE,
    contractType: "Output",
    capitalSource: "StateBudget",
    constructionType: "Dân dụng",
    location: "TP. Hồ Chí Minh",
    personnel: [],
    paymentMilestones: [],
    transactions: []
  },
  // HĐ 10/BIM-CICHD2025 - Bảo tàng Chăm
  {
    id: "10/BIM-CICHD2025",
    code: "10/BIM-CICHD2025",
    projectName: "Bảo tàng Điêu khắc Chăm",
    projectId: "P-029",
    sideAName: "BQL DA ĐT XD CT DD, CN & HTKT ĐÀ NẴNG",
    sideARep: "",
    sideBName: "CÔNG TY CP CÔNG NGHỆ VÀ TƯ VẤN CIC",
    sideBRep: "",
    packageName: "Tư vấn BIM",
    signedDate: "2025-03-01",
    startDate: "2025-03-01",
    endDate: "2025-08-31",
    duration: "6 tháng",
    totalValue: 270570000,
    paidValue: 135285000,
    remainingValue: 135285000,
    vatIncluded: true,
    advancePayment: 50,
    status: ContractStatus.ACTIVE,
    contractType: "Output",
    capitalSource: "StateBudget",
    constructionType: "Dân dụng",
    location: "Đà Nẵng",
    personnel: [],
    paymentMilestones: [],
    transactions: []
  },
  // HĐ 41/BIM-CICHD2025 - Mở rộng BV Sản nhi Quảng Ninh
  {
    id: "41/BIM-CICHD2025",
    code: "41/BIM-CICHD2025",
    projectName: "Mở rộng Bệnh viện Sản nhi Quảng Ninh - GĐ II",
    projectId: "P-030",
    sideAName: "BQL DA ĐT XD KHU VỰC I TỈNH QUẢNG NINH",
    sideARep: "",
    sideBName: "CÔNG TY CP CÔNG NGHỆ VÀ TƯ VẤN CIC",
    sideBRep: "",
    packageName: "Tư vấn BIM",
    signedDate: "2025-05-01",
    startDate: "2025-05-01",
    endDate: "2025-12-31",
    duration: "8 tháng",
    totalValue: 651951180,
    paidValue: 195585354,
    remainingValue: 456365826,
    vatIncluded: true,
    advancePayment: 30,
    status: ContractStatus.ACTIVE,
    contractType: "Output",
    capitalSource: "StateBudget",
    constructionType: "Dân dụng",
    location: "Quảng Ninh",
    personnel: [],
    paymentMilestones: [],
    transactions: []
  },
  // HĐ 42/BIM-CICHD2025 - Chung cư NOXH Uyên Hưng
  {
    id: "42/BIM-CICHD2025",
    code: "42/BIM-CICHD2025",
    projectName: "Chung cư Nhà ở xã hội Uyên Hưng",
    projectId: "P-031",
    sideAName: "CÔNG TY CP XÂY DỰNG TƯ VẤN ĐẦU TƯ BÌNH DƯƠNG",
    sideARep: "",
    sideBName: "CÔNG TY CP CÔNG NGHỆ VÀ TƯ VẤN CIC",
    sideBRep: "",
    packageName: "Tư vấn BIM",
    signedDate: "2025-06-01",
    startDate: "2025-06-01",
    endDate: "2026-06-30",
    duration: "12 tháng",
    totalValue: 1400000000,
    paidValue: 420000000,
    remainingValue: 980000000,
    vatIncluded: true,
    advancePayment: 30,
    status: ContractStatus.ACTIVE,
    contractType: "Output",
    capitalSource: "NonStateBudget",
    constructionType: "Dân dụng",
    location: "Bình Dương",
    personnel: [],
    paymentMilestones: [],
    transactions: []
  },
  // HĐ 40/BIM-CICHD2025 - NOXH Hà Tĩnh
  {
    id: "40/BIM-CICHD2025",
    code: "40/BIM-CICHD2025",
    projectName: "Nhà ở xã hội Hà Tĩnh",
    projectId: "P-032",
    sideAName: "QUỸ ĐẦU TƯ PHÁT TRIỂN HÀ TĨNH",
    sideARep: "",
    sideBName: "CÔNG TY CP CÔNG NGHỆ VÀ TƯ VẤN CIC",
    sideBRep: "",
    packageName: "Tư vấn BIM",
    signedDate: "2025-05-15",
    startDate: "2025-05-15",
    endDate: "2025-12-31",
    duration: "8 tháng",
    totalValue: 242149000,
    paidValue: 72644700,
    remainingValue: 169504300,
    vatIncluded: true,
    advancePayment: 30,
    status: ContractStatus.ACTIVE,
    contractType: "Output",
    capitalSource: "StateBudget",
    constructionType: "Dân dụng",
    location: "Hà Tĩnh",
    personnel: [],
    paymentMilestones: [],
    transactions: []
  },
  // HĐ 44/BIM-CICHD2025 - BV Phục hồi chức năng
  {
    id: "44/BIM-CICHD2025",
    code: "44/BIM-CICHD2025",
    projectName: "Bệnh viện Phục hồi chức năng - Điều trị bệnh nghề nghiệp",
    projectId: "P-033",
    sideAName: "BQL DA ĐT XD CT DD & CN TP.HCM",
    sideARep: "",
    sideBName: "CÔNG TY CP CÔNG NGHỆ VÀ TƯ VẤN CIC",
    sideBRep: "",
    packageName: "Tư vấn BIM",
    signedDate: "2025-05-01",
    startDate: "2025-05-01",
    endDate: "2025-11-30",
    duration: "7 tháng",
    totalValue: 685209000,
    paidValue: 205562700,
    remainingValue: 479646300,
    vatIncluded: true,
    advancePayment: 30,
    status: ContractStatus.ACTIVE,
    contractType: "Output",
    capitalSource: "StateBudget",
    constructionType: "Dân dụng",
    location: "TP. Hồ Chí Minh",
    personnel: [],
    paymentMilestones: [],
    transactions: []
  },
  // HĐ 45/BIM-CICHD2025 - BV Đa khoa YHCT Hà Nội
  {
    id: "45/BIM-CICHD2025",
    code: "45/BIM-CICHD2025",
    projectName: "Bệnh viện Đa khoa Y học cổ truyền Hà Nội",
    projectId: "P-034",
    sideAName: "BQL DA ĐT XD CT DD & CN HÀ NỘI",
    sideARep: "",
    sideBName: "CÔNG TY CP CÔNG NGHỆ VÀ TƯ VẤN CIC",
    sideBRep: "",
    packageName: "Tư vấn BIM",
    signedDate: "2025-05-15",
    startDate: "2025-05-15",
    endDate: "2025-12-31",
    duration: "8 tháng",
    totalValue: 925390000,
    paidValue: 277617000,
    remainingValue: 647773000,
    vatIncluded: true,
    advancePayment: 30,
    status: ContractStatus.ACTIVE,
    contractType: "Output",
    capitalSource: "StateBudget",
    constructionType: "Dân dụng",
    location: "Hà Nội",
    personnel: [],
    paymentMilestones: [],
    transactions: []
  },
  // HĐ 46/BIM-CICHD2025 - Trường Chuyên biệt Hà Nội
  {
    id: "46/BIM-CICHD2025",
    code: "46/BIM-CICHD2025",
    projectName: "Trường Chuyên biệt cho trẻ em khuyết tật Hà Nội",
    projectId: "P-035",
    sideAName: "BQL DA ĐT XD CT DD & CN HÀ NỘI",
    sideARep: "",
    sideBName: "CÔNG TY CP CÔNG NGHỆ VÀ TƯ VẤN CIC",
    sideBRep: "",
    packageName: "Tư vấn BIM",
    signedDate: "2025-04-01",
    startDate: "2025-04-01",
    endDate: "2025-10-31",
    duration: "7 tháng",
    totalValue: 380401000,
    paidValue: 114120300,
    remainingValue: 266280700,
    vatIncluded: true,
    advancePayment: 30,
    status: ContractStatus.ACTIVE,
    contractType: "Output",
    capitalSource: "StateBudget",
    constructionType: "Dân dụng",
    location: "Hà Nội",
    personnel: [],
    paymentMilestones: [],
    transactions: []
  },
  // HĐ 48/BIM-CICHD2025 - BV Nhi đồng 2
  {
    id: "48/BIM-CICHD2025",
    code: "48/BIM-CICHD2025",
    projectName: "Bệnh viện Nhi đồng 2 - Khối Nhiệt đới",
    projectId: "P-036",
    sideAName: "BQL DA ĐT XD CT DD & CN TP.HCM",
    sideARep: "",
    sideBName: "CÔNG TY CP CÔNG NGHỆ VÀ TƯ VẤN CIC",
    sideBRep: "",
    packageName: "Tư vấn BIM",
    signedDate: "2025-05-15",
    startDate: "2025-05-15",
    endDate: "2025-11-30",
    duration: "7 tháng",
    totalValue: 734191500,
    paidValue: 220257450,
    remainingValue: 513934050,
    vatIncluded: true,
    advancePayment: 30,
    status: ContractStatus.ACTIVE,
    contractType: "Output",
    capitalSource: "StateBudget",
    constructionType: "Dân dụng",
    location: "TP. Hồ Chí Minh",
    personnel: [],
    paymentMilestones: [],
    transactions: []
  },
  // HĐ 50/BIM-CICHD2025 - Eco Smart City Plot Cần Giờ
  {
    id: "50/BIM-CICHD2025",
    code: "50/BIM-CICHD2025",
    projectName: "Eco Smart City Plot Cần Giờ",
    projectId: "P-037",
    sideAName: "CÔNG TY TNHH DỊCH VỤ TƯ VẤN THIẾT KẾ CDS",
    sideARep: "",
    sideBName: "CÔNG TY CP CÔNG NGHỆ VÀ TƯ VẤN CIC",
    sideBRep: "",
    packageName: "Tư vấn BIM",
    signedDate: "2025-06-01",
    startDate: "2025-06-01",
    endDate: "2026-03-31",
    duration: "10 tháng",
    totalValue: 231000000,
    paidValue: 69300000,
    remainingValue: 161700000,
    vatIncluded: true,
    advancePayment: 30,
    status: ContractStatus.ACTIVE,
    contractType: "Output",
    capitalSource: "NonStateBudget",
    constructionType: "Dân dụng",
    location: "TP. Hồ Chí Minh",
    personnel: [],
    paymentMilestones: [],
    transactions: []
  },
  // HĐ 53/BIM-CICHD2025 - NOXH Pháp Vân - Tứ Hiệp
  {
    id: "53/BIM-CICHD2025",
    code: "53/BIM-CICHD2025",
    projectName: "Nhà ở xã hội Pháp Vân - Tứ Hiệp",
    projectId: "P-038",
    sideAName: "BQL DA ĐT XD CT DD & CN HÀ NỘI",
    sideARep: "",
    sideBName: "CÔNG TY CP CÔNG NGHỆ VÀ TƯ VẤN CIC",
    sideBRep: "",
    packageName: "Tư vấn BIM",
    signedDate: "2025-06-01",
    startDate: "2025-06-01",
    endDate: "2026-03-31",
    duration: "10 tháng",
    totalValue: 309818000,
    paidValue: 92945400,
    remainingValue: 216872600,
    vatIncluded: true,
    advancePayment: 30,
    status: ContractStatus.ACTIVE,
    contractType: "Output",
    capitalSource: "StateBudget",
    constructionType: "Dân dụng",
    location: "Hà Nội",
    personnel: [],
    paymentMilestones: [],
    transactions: []
  },
  // HĐ 55/BIM-CICHD2025 - Trường THPT Bãi Cháy GĐ2
  {
    id: "55/BIM-CICHD2025",
    code: "55/BIM-CICHD2025",
    projectName: "Trường THPT Bãi Cháy - Giai đoạn 2",
    projectId: "P-039",
    sideAName: "BAN QUẢN LÝ DỰ ÁN ĐẦU TƯ XÂY DỰNG",
    sideARep: "",
    sideBName: "CÔNG TY CP CÔNG NGHỆ VÀ TƯ VẤN CIC",
    sideBRep: "",
    packageName: "Tư vấn BIM",
    signedDate: "2025-06-15",
    startDate: "2025-06-15",
    endDate: "2025-12-31",
    duration: "7 tháng",
    totalValue: 624036000,
    paidValue: 187210800,
    remainingValue: 436825200,
    vatIncluded: true,
    advancePayment: 30,
    status: ContractStatus.ACTIVE,
    contractType: "Output",
    capitalSource: "StateBudget",
    constructionType: "Dân dụng",
    location: "Quảng Ninh",
    personnel: [],
    paymentMilestones: [],
    transactions: []
  }
];

// Customer mapping based on sideAName patterns
const CUSTOMER_NAME_TO_ID: Record<string, string> = {
  'BAN QUẢN LÝ DỰ ÁN ĐẦU TƯ XÂY DỰNG CHUYÊN NGÀNH': 'CUST-001',
  'VIGLACERA': 'CUST-002',
  'BQL DA ĐT XD CT DD & CN TP.HCM': 'CUST-003',
  'CÔNG TY CỔ PHẦN 319.5': 'CUST-004',

  'VIỆN KIẾN TRÚC QUỐC GIA': 'CUST-005',
  'VIỆT PANEL': 'CUST-006',
  'VCC': 'CUST-007',
  'CÔNG TY CP SẢN XUẤT CÔNG NGHIỆP XÂY LẮP 3': 'CUST-008',
  'CDC': 'CUST-009',
  'BQL DA DDCN QUẢNG NINH': 'CUST-010',
  'JUNGLIM': 'CUST-011',
  'KCN AN HÒA': 'CUST-012',
  'HUD': 'CUST-013',
  'VĂN PHÒNG TƯ VẤN': 'CUST-014',
  'BQL DA DDHT HÀ TĨNH': 'CUST-015',
  'THỊNH VƯỢNG MINH CHÂU': 'CUST-016',
  'STELLAR': 'CUST-017',
  'BQL DA DDCN ĐÀ NẴNG': 'CUST-018',
  'BQL DA KV1': 'CUST-019',
  'XD TV ĐT BÌNH DƯƠNG': 'CUST-020',
  'QUỸ ĐẦU TƯ': 'CUST-021',
  'BQL DA DDCN HÀ NỘI': 'CUST-022',
  'CDS': 'CUST-023',
  'BAN QUẢN LÝ DỰ ÁN ĐẦU TƯ XÂY DỰNG': 'CUST-024',
};

// Helper to find customerId from sideAName
const findCustomerId = (sideAName: string | undefined): string | undefined => {
  if (!sideAName) return undefined;
  const upperName = sideAName.toUpperCase();

  // Try exact match first
  for (const [pattern, customerId] of Object.entries(CUSTOMER_NAME_TO_ID)) {
    if (upperName.includes(pattern.toUpperCase())) {
      return customerId;
    }
  }

  // Fallback patterns
  if (upperName.includes('VIGLACERA')) return 'CUST-002';
  if (upperName.includes('NHI ĐỒNG') || upperName.includes('TP.HCM') || upperName.includes('THÀNH PHỐ HỒ CHÍ MINH')) return 'CUST-003';
  if (upperName.includes('319.5')) return 'CUST-004';
  if (upperName.includes('VIỆT PANEL')) return 'CUST-006';
  if (upperName.includes('VCC') || upperName.includes('TƯ VẤN XÂY DỰNG CÔNG NGHIỆP')) return 'CUST-007';
  if (upperName.includes('XÂY LẮP 3')) return 'CUST-008';
  if (upperName.includes('CDC') || upperName.includes('THIẾT KẾ XÂY DỰNG VIỆT NAM')) return 'CUST-009';
  if (upperName.includes('QUẢNG NINH')) return 'CUST-010';
  if (upperName.includes('JUNGLIM')) return 'CUST-011';
  if (upperName.includes('AN HÒA')) return 'CUST-012';
  if (upperName.includes('HUD') || upperName.includes('PHÁT TRIỂN NHÀ')) return 'CUST-013';
  if (upperName.includes('HÀ TĨNH')) return 'CUST-015';
  if (upperName.includes('MINH CHÂU')) return 'CUST-016';
  if (upperName.includes('STELLAR')) return 'CUST-017';
  if (upperName.includes('ĐÀ NẴNG')) return 'CUST-018';
  if (upperName.includes('KV1') || upperName.includes('KHU VỰC I')) return 'CUST-019';
  if (upperName.includes('BÌNH DƯƠNG')) return 'CUST-020';
  if (upperName.includes('QUỸ')) return 'CUST-021';
  if (upperName.includes('HÀ NỘI') && upperName.includes('BQL')) return 'CUST-022';
  if (upperName.includes('CDS')) return 'CUST-023';

  return undefined;
};

// Export contracts with default values and customerId mapped
export const CONTRACTS: Contract[] = RAW_CONTRACTS.map(c => ({
  ...defaultContractFields,
  ...c,
  customerId: findCustomerId(c.sideAName)
} as Contract));