import { Customer } from '../types';

// Customers extracted from DATA.pdf - linked to Projects and Contracts
export const CUSTOMERS: Customer[] = [
  // CUST-001: BQL DA ĐT XD Chuyên ngành (Bộ KHCN)
  {
    id: "CUST-001",
    code: "BQLDA-CN",
    name: "BAN QUẢN LÝ DỰ ÁN ĐẦU TƯ XÂY DỰNG CHUYÊN NGÀNH",
    shortName: "BQL DA Chuyên ngành",
    type: "Client",
    category: "StateBudget",
    status: "Active",
    representative: "Nguyễn In",
    contactPerson: "Nguyễn In",
    phone: "",
    email: "",
    address: "Hà Nội",
    taxCode: "",
    tier: "Gold",
    totalProjectValue: 381800000,
    logo: "https://via.placeholder.com/100x100?text=BQLDA"
  },
  // CUST-002: Viglacera BQLDA
  {
    id: "CUST-002",
    code: "VIG-BQLDA",
    name: "BAN QUẢN LÝ CÁC DỰ ÁN ĐẦU TƯ XÂY DỰNG - CHI NHÁNH TỔNG CÔNG TY VIGLACERA - CTCP",
    shortName: "Viglacera BQLDA",
    type: "Client",
    category: "RealEstate",
    status: "Active",
    representative: "Trần Anh Tuấn",
    contactPerson: "Trần Anh Tuấn",
    phone: "",
    email: "",
    address: "Yên Bái",
    taxCode: "",
    tier: "Gold",
    totalProjectValue: 259200000,
    logo: "https://via.placeholder.com/100x100?text=VIG"
  },
  // CUST-003: BQL DA ĐT XD CT DD & CN TP.HCM
  {
    id: "CUST-003",
    code: "BQLDA-HCM",
    name: "BAN QUẢN LÝ DỰ ÁN ĐẦU TƯ XÂY DỰNG CÔNG TRÌNH DÂN DỤNG VÀ CÔNG NGHIỆP THÀNH PHỐ HỒ CHÍ MINH",
    shortName: "BQL DA DDCN TP.HCM",
    type: "Client",
    category: "StateBudget",
    status: "Active",
    representative: "Huỳnh Thanh Hải",
    contactPerson: "Dương Minh Thủy",
    phone: "",
    email: "",
    address: "TP. Hồ Chí Minh",
    taxCode: "",
    tier: "VIP",
    totalProjectValue: 7000000000,
    logo: "https://via.placeholder.com/100x100?text=BQLDA-HCM"
  },
  // CUST-004: Công ty CP 319.5
  {
    id: "CUST-004",
    code: "319.5",
    name: "CÔNG TY CỔ PHẦN 319.5",
    shortName: "Công ty CP 319.5",
    type: "Client",
    category: "Construction",
    status: "Active",
    representative: "Nguyễn Ngọc Niệm",
    contactPerson: "Nguyễn Ngọc Niệm",
    phone: "",
    email: "",
    address: "Hà Nội",
    taxCode: "",
    tier: "Gold",
    totalProjectValue: 891000000,
    logo: "https://via.placeholder.com/100x100?text=319.5"
  },
  // CUST-005: Viện Kiến trúc Quốc gia
  {
    id: "CUST-005",
    code: "VKTQG",
    name: "VIỆN KIẾN TRÚC QUỐC GIA",
    shortName: "Viện KTQG",
    type: "Partner",
    category: "Consulting",
    status: "Active",
    representative: "Nhật",
    contactPerson: "Nhật",
    phone: "",
    email: "",
    address: "Hà Nội",
    taxCode: "",
    tier: "Gold",
    totalProjectValue: 495811000,
    logo: "https://via.placeholder.com/100x100?text=VKTQG"
  },
  // CUST-006: Việt Panel
  {
    id: "CUST-006",
    code: "VIETPANEL",
    name: "CÔNG TY TNHH XÂY DỰNG VIỆT PANEL",
    shortName: "Việt Panel",
    type: "Client",
    category: "Construction",
    status: "Active",
    representative: "Lưu Bình Cii",
    contactPerson: "Lưu Bình Cii",
    phone: "",
    email: "",
    address: "Vĩnh Phúc",
    taxCode: "",
    tier: "Standard",
    totalProjectValue: 122000000,
    logo: "https://via.placeholder.com/100x100?text=VPANEL"
  },
  // CUST-007: VCC
  {
    id: "CUST-007",
    code: "VCC",
    name: "CÔNG TY CỔ PHẦN TƯ VẤN XÂY DỰNG CÔNG NGHIỆP VÀ ĐÔ THỊ VIỆT NAM",
    shortName: "VCC",
    type: "Client",
    category: "Consulting",
    status: "Active",
    representative: "Hoàng Thị Ngọc Loan",
    contactPerson: "Hoàng Thị Ngọc Loan",
    phone: "",
    email: "",
    address: "Hà Nội",
    taxCode: "",
    tier: "VIP",
    totalProjectValue: 951106270,
    logo: "https://via.placeholder.com/100x100?text=VCC"
  },
  // CUST-008: Công ty CP SXCN Xây lắp 3
  {
    id: "CUST-008",
    code: "CNXL3",
    name: "CÔNG TY CỔ PHẦN SẢN XUẤT CÔNG NGHIỆP XÂY LẮP 3",
    shortName: "CNXL 3",
    type: "Client",
    category: "Construction",
    status: "Active",
    representative: "Lã Tiến Lực",
    contactPerson: "Lã Tiến Lực",
    phone: "",
    email: "",
    address: "Hà Nội",
    taxCode: "",
    tier: "Gold",
    totalProjectValue: 891000000,
    logo: "https://via.placeholder.com/100x100?text=CNXL3"
  },
  // CUST-009: CDC
  {
    id: "CUST-009",
    code: "CDC",
    name: "CÔNG TY CỔ PHẦN TƯ VẤN VÀ THIẾT KẾ XÂY DỰNG VIỆT NAM",
    shortName: "CDC",
    type: "Client",
    category: "Consulting",
    status: "Active",
    representative: "Trần Tuấn Anh",
    contactPerson: "Trần Tuấn Anh",
    phone: "",
    email: "",
    address: "Hà Nội",
    taxCode: "",
    tier: "Gold",
    totalProjectValue: 363960000,
    logo: "https://via.placeholder.com/100x100?text=CDC"
  },
  // CUST-010: BQL DA DDCN Quảng Ninh
  {
    id: "CUST-010",
    code: "BQLDA-QN",
    name: "BAN QUẢN LÝ DỰ ÁN ĐẦU TƯ XÂY DỰNG CÔNG TRÌNH DÂN DỤNG VÀ CÔNG NGHIỆP QUẢNG NINH",
    shortName: "BQL DA DDCN QN",
    type: "Client",
    category: "StateBudget",
    status: "Active",
    representative: "Nguyễn Văn Chí",
    contactPerson: "Nguyễn Văn Chí",
    phone: "",
    email: "",
    address: "Quảng Ninh",
    taxCode: "",
    tier: "Gold",
    totalProjectValue: 670036000,
    logo: "https://via.placeholder.com/100x100?text=BQLDA-QN"
  },
  // CUST-011: Junglim Architecture Vietnam
  {
    id: "CUST-011",
    code: "JUNGLIM",
    name: "CÔNG TY TNHH JUNGLIM ARCHITECTURE VIETNAM",
    shortName: "Junglim",
    type: "Client",
    category: "RealEstate",
    status: "Active",
    representative: "",
    contactPerson: "",
    phone: "",
    email: "",
    address: "TP. Hồ Chí Minh",
    taxCode: "",
    tier: "VIP",
    totalProjectValue: 3583000000,
    logo: "https://via.placeholder.com/100x100?text=JUNGLIM"
  },
  // CUST-012: Công ty CP KCN An Hòa
  {
    id: "CUST-012",
    code: "KCN-ANHOA",
    name: "CÔNG TY CỔ PHẦN KHU CÔNG NGHIỆP VÀ ĐÔ THỊ AN HÒA",
    shortName: "KCN An Hòa",
    type: "Client",
    category: "RealEstate",
    status: "Active",
    representative: "",
    contactPerson: "",
    phone: "",
    email: "",
    address: "Quảng Nam",
    taxCode: "",
    tier: "Gold",
    totalProjectValue: 388800000,
    logo: "https://via.placeholder.com/100x100?text=KCN-AH"
  },
  // CUST-013: HUD
  {
    id: "CUST-013",
    code: "HUD",
    name: "TỔNG CÔNG TY ĐẦU TƯ PHÁT TRIỂN NHÀ VÀ ĐÔ THỊ",
    shortName: "HUD",
    type: "Client",
    category: "RealEstate",
    status: "Active",
    representative: "",
    contactPerson: "",
    phone: "",
    email: "",
    address: "Hà Nội",
    taxCode: "",
    tier: "Gold",
    totalProjectValue: 180000000,
    logo: "https://via.placeholder.com/100x100?text=HUD"
  },
  // CUST-014: VP Tư vấn & CG Công nghệ XD
  {
    id: "CUST-014",
    code: "VP-TVCG",
    name: "VĂN PHÒNG TƯ VẤN VÀ CHUYỂN GIAO CÔNG NGHỆ XÂY DỰNG",
    shortName: "VP TV & CG CNXD",
    type: "Partner",
    category: "Consulting",
    status: "Active",
    representative: "",
    contactPerson: "",
    phone: "",
    email: "",
    address: "Hà Nội",
    taxCode: "",
    tier: "VIP",
    totalProjectValue: 1946502000,
    logo: "https://via.placeholder.com/100x100?text=VP-TVCG"
  },
  // CUST-015: BQL DA DDHT Hà Tĩnh
  {
    id: "CUST-015",
    code: "BQLDA-HT",
    name: "BAN QUẢN LÝ DỰ ÁN ĐẦU TƯ XÂY DỰNG CÔNG TRÌNH DÂN DỤNG VÀ HẠ TẦNG HÀ TĨNH",
    shortName: "BQL DA DDHT Hà Tĩnh",
    type: "Client",
    category: "StateBudget",
    status: "Active",
    representative: "",
    contactPerson: "",
    phone: "",
    email: "",
    address: "Hà Tĩnh",
    taxCode: "",
    tier: "Gold",
    totalProjectValue: 456169000,
    logo: "https://via.placeholder.com/100x100?text=BQLDA-HT"
  },
  // CUST-016: Thịnh Vượng Minh Châu
  {
    id: "CUST-016",
    code: "TVMC",
    name: "CÔNG TY CỔ PHẦN THỊNH VƯỢNG MINH CHÂU",
    shortName: "Thịnh Vượng MC",
    type: "Client",
    category: "RealEstate",
    status: "Active",
    representative: "",
    contactPerson: "",
    phone: "",
    email: "",
    address: "Hưng Yên",
    taxCode: "",
    tier: "Standard",
    totalProjectValue: 100000000,
    logo: "https://via.placeholder.com/100x100?text=TVMC"
  },
  // CUST-017: Stellar
  {
    id: "CUST-017",
    code: "STELLAR",
    name: "CÔNG TY CỔ PHẦN THIẾT KẾ XÂY DỰNG STELLAR",
    shortName: "Stellar",
    type: "Client",
    category: "RealEstate",
    status: "Active",
    representative: "",
    contactPerson: "",
    phone: "",
    email: "",
    address: "Hà Nội",
    taxCode: "",
    tier: "VIP",
    totalProjectValue: 3448000000,
    logo: "https://via.placeholder.com/100x100?text=STELLAR"
  },
  // CUST-018: BQL DA DDCN Đà Nẵng
  {
    id: "CUST-018",
    code: "BQLDA-DN",
    name: "BAN QUẢN LÝ DỰ ÁN ĐẦU TƯ XÂY DỰNG CÔNG TRÌNH DÂN DỤNG, CÔNG NGHIỆP VÀ HẠ TẦNG KỸ THUẬT ĐÀ NẴNG",
    shortName: "BQL DA DDCN Đà Nẵng",
    type: "Client",
    category: "StateBudget",
    status: "Active",
    representative: "",
    contactPerson: "",
    phone: "",
    email: "",
    address: "Đà Nẵng",
    taxCode: "",
    tier: "Gold",
    totalProjectValue: 270570000,
    logo: "https://via.placeholder.com/100x100?text=BQLDA-DN"
  },
  // CUST-019: BQL DA KV1 Quảng Ninh
  {
    id: "CUST-019",
    code: "BQLDA-KV1-QN",
    name: "BAN QUẢN LÝ DỰ ÁN ĐẦU TƯ XÂY DỰNG KHU VỰC I TỈNH QUẢNG NINH",
    shortName: "BQL DA KV1 QN",
    type: "Client",
    category: "StateBudget",
    status: "Active",
    representative: "",
    contactPerson: "",
    phone: "",
    email: "",
    address: "Quảng Ninh",
    taxCode: "",
    tier: "Gold",
    totalProjectValue: 651951180,
    logo: "https://via.placeholder.com/100x100?text=BQLDA-KV1"
  },
  // CUST-020: XD TV ĐT Bình Dương
  {
    id: "CUST-020",
    code: "XDDT-BD",
    name: "CÔNG TY CỔ PHẦN XÂY DỰNG TƯ VẤN ĐẦU TƯ BÌNH DƯƠNG",
    shortName: "XD TV ĐT Bình Dương",
    type: "Client",
    category: "RealEstate",
    status: "Active",
    representative: "",
    contactPerson: "",
    phone: "",
    email: "",
    address: "Bình Dương",
    taxCode: "",
    tier: "VIP",
    totalProjectValue: 1400000000,
    logo: "https://via.placeholder.com/100x100?text=XDDT-BD"
  },
  // CUST-021: Quỹ ĐT Hà Tĩnh
  {
    id: "CUST-021",
    code: "QDT-HT",
    name: "QUỸ ĐẦU TƯ PHÁT TRIỂN HÀ TĨNH",
    shortName: "Quỹ ĐT Hà Tĩnh",
    type: "Client",
    category: "StateBudget",
    status: "Active",
    representative: "",
    contactPerson: "",
    phone: "",
    email: "",
    address: "Hà Tĩnh",
    taxCode: "",
    tier: "Standard",
    totalProjectValue: 242149000,
    logo: "https://via.placeholder.com/100x100?text=QDT-HT"
  },
  // CUST-022: BQL DA DDCN Hà Nội
  {
    id: "CUST-022",
    code: "BQLDA-HN",
    name: "BAN QUẢN LÝ DỰ ÁN ĐẦU TƯ XÂY DỰNG CÔNG TRÌNH DÂN DỤNG VÀ CÔNG NGHIỆP HÀ NỘI",
    shortName: "BQL DA DDCN Hà Nội",
    type: "Client",
    category: "StateBudget",
    status: "Active",
    representative: "",
    contactPerson: "",
    phone: "",
    email: "",
    address: "Hà Nội",
    taxCode: "",
    tier: "VIP",
    totalProjectValue: 1925427000,
    logo: "https://via.placeholder.com/100x100?text=BQLDA-HN"
  },
  // CUST-023: CDS
  {
    id: "CUST-023",
    code: "CDS",
    name: "CÔNG TY TNHH DỊCH VỤ TƯ VẤN THIẾT KẾ CDS",
    shortName: "CDS",
    type: "Client",
    category: "Consulting",
    status: "Active",
    representative: "",
    contactPerson: "",
    phone: "",
    email: "",
    address: "TP. Hồ Chí Minh",
    taxCode: "",
    tier: "Standard",
    totalProjectValue: 231000000,
    logo: "https://via.placeholder.com/100x100?text=CDS"
  },
  // CUST-024: BQL DA ĐT XD
  {
    id: "CUST-024",
    code: "BQLDA-DTXD",
    name: "BAN QUẢN LÝ DỰ ÁN ĐẦU TƯ XÂY DỰNG",
    shortName: "BQL DA ĐT XD",
    type: "Client",
    category: "StateBudget",
    status: "Active",
    representative: "",
    contactPerson: "",
    phone: "",
    email: "",
    address: "Quảng Ninh",
    taxCode: "",
    tier: "Gold",
    totalProjectValue: 624036000,
    logo: "https://via.placeholder.com/100x100?text=BQLDA-DTXD"
  }
];

// Legacy CRM Customer Data (kept for compatibility with existing CRM module)
export const MOCK_CRM_CUSTOMERS = CUSTOMERS;